title:              Victor Murcia
email:              victor.murcia@wsu.edu
description:        Data Scientist • Algorithm Developer • Computational Chemist/Physicist • Materials Scientist and Engineer
author:             Victor Murcia
baseurl:            ""
url:                "https://victormurcia.github.io"

# Social Profiles
twitter_username:   
github_username:    victormurcia
facebook_username:  vmurcia2
instagram_username:  
linkedin_username:  vmmr5596

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           7
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
